----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.in aclocal.m4 configure configure.ac src/Makefile.am
 	src/Makefile.in src/MoochoUtilities/Range1D.cpp
 	src/MoochoUtilities/Range1D.hpp
 	src/MoochoUtilities/StandardCompositionRelationshipsPack.hpp
 	src/MoochoUtilities/ThrowException.hpp
 	src/MoochoUtilities/WorkspacePack.cpp
 	src/MoochoUtilities/WorkspacePack.hpp
 	src/MoochoUtilities/dynamic_cast_verbose.cpp
 	src/MoochoUtilities/dynamic_cast_verbose.hpp
 	src/MoochoUtilities/ref_count_ptr.cpp
 	src/MoochoUtilities/ref_count_ptr_decl.hpp
 	src/RTOpPack/RTOpCpp.hpp src/RTOpPack/RTOpCppC.cpp
 	src/RTOpPack/RTOpCppDecl.hpp src/RTOpPack/RTOpCppToMPI.cpp
 	src/RTOpPack/RTOpPackTypes.hpp
 	src/RTOpPack/RTOp_RTOp_C_Cpp.cpp src/RTOpPack/RTOp_config.h
 	src/RTOpPack/check_nan_inf.cpp
 	src/RTOpPack/print_sub_vector.cpp
 	src/RTOpPack/print_sub_vector.hpp test/Makefile.in
 	test/rcp_test/Makefile.am test/rcp_test/Makefile.in
 ----------------------------------------------------------------------

 Changed headers to use configurable header file created through autoconf.

diff --git a/packages/TSFCoreUtils/configure b/packages/TSFCoreUtils/configure
--- a/packages/TSFCoreUtils/configure
+++ b/packages/TSFCoreUtils/configure
@@ -1383,7 +1383,7 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 
 # Add the stamp file to the list of files AC keeps track of,
 # along with our hook.
-          ac_config_headers="$ac_config_headers src/MoochoUtilities/TSFCoreUtilsConfig.h:src/MoochoUtilities/TSFCoreUtilsConfig.h.in"
+          ac_config_headers="$ac_config_headers src/TSFCoreUtilsConfig.h:src/TSFCoreUtilsConfig.h.in"
 
 
 
@@ -4581,7 +4581,8 @@ done
 
 
 
-for ac_header in cmath math.h iomanip iomanip.h iostream iostream.h
+
+for ac_header in cmath math.h iomanip iomanip.h ostream iostream iostream.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -4724,7 +4725,157 @@ done
 
 
 
-for ac_header in string string.h
+
+
+
+for ac_header in string string.h malloc.h sstream stdexcept
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
+
+
+
+
+
+
+
+for ac_header in memory memory.h typeinfo limits.h new iosfwd
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -4890,25 +5041,46 @@ echo "$as_me: error: Cannot find string or string.h.  New_Package requires at le
    { (exit 1); exit 1; }; }
 fi
 
-if test "X$ac_cv_header_iostream" != "Xyes" && test "X$ac_cv_header_iostream_h" != "Xyes"; then
+if test "X$ac_cv_header_ostream" != "Xyes" && test "X$ac_cv_header_iostream" != "Xyes" && test "X$ac_cv_header_iostream_h" != "Xyes"; then
   { { echo "$as_me:$LINENO: error: Cannot find iostream or iostream.h.  New_Package requires at least one or the other." >&5
 echo "$as_me: error: Cannot find iostream or iostream.h.  New_Package requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-if test "X${host}" != "Xtflop"; then
-  if test "X$ac_cv_header_cmath" != "Xyes" && test "X$ac_cv_header_math_h" != "Xyes"; then
+if test "X$ac_cv_header_cmath" != "Xyes" && test "X$ac_cv_header_math_h" != "Xyes"; then
     { { echo "$as_me:$LINENO: error: Cannot find cmath or math.h.  New_Package requires at least one or the other." >&5
 echo "$as_me: error: Cannot find cmath or math.h.  New_Package requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
-  fi
-else
-  # TFLOP
-  if test "X$ac_cv_header_iomanip" != "Xyes" && test "X$ac_cv_header_iomanip_h" != "Xyes"; then
+fi
+
+if test "X$ac_cv_header_iomanip" != "Xyes" && test "X$ac_cv_header_iomanip_h" != "Xyes"; then
     { { echo "$as_me:$LINENO: error: Cannot find iomanip or iomanip.h.  New_Package requires at least one or the other." >&5
 echo "$as_me: error: Cannot find iomanip or iomanip.h.  New_Package requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
-  fi
+fi
+
+if test "X$ac_cv_header_malloc_h" != "Xyes"; then
+    { { echo "$as_me:$LINENO: error: Cannot find malloc.h.  New_Package requires at least one or the other." >&5
+echo "$as_me: error: Cannot find malloc.h.  New_Package requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_sstream" != "Xyes"; then
+    { { echo "$as_me:$LINENO: error: Cannot find sstream.  New_Package requires at least one or the other." >&5
+echo "$as_me: error: Cannot find sstream.  New_Package requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_stdexcept" != "Xyes"; then
+    { { echo "$as_me:$LINENO: error: Cannot find stdexcept.  New_Package requires at least one or the other." >&5
+echo "$as_me: error: Cannot find stdexcept.  New_Package requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_memory" != "Xyes" && test "X$ac_cv_header_memory_h" != "Xyes"; then
+    { { echo "$as_me:$LINENO: error: Cannot find memory or memory.h.  New_Package requires at least one or the other." >&5
+echo "$as_me: error: Cannot find memory or memory.h.  New_Package requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 # Checks for typedefs, structures, and compiler characteristics.
@@ -5738,7 +5910,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5741: \"$ac_link\") >&5
+(eval echo $as_me:5913: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5818,7 +5990,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5821: \"$ac_link\") >&5
+(eval echo $as_me:5993: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6721,7 +6893,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:6724: \"$ac_link\") >&5
+(eval echo $as_me:6896: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6801,7 +6973,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6804: \"$ac_link\") >&5
+(eval echo $as_me:6976: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7604,7 +7776,7 @@ do
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
   "test/rcp_test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/rcp_test/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
-  "src/MoochoUtilities/TSFCoreUtilsConfig.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/MoochoUtilities/TSFCoreUtilsConfig.h:src/MoochoUtilities/TSFCoreUtilsConfig.h.in" ;;
+  "src/TSFCoreUtilsConfig.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/TSFCoreUtilsConfig.h:src/TSFCoreUtilsConfig.h.in" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
@@ -8189,8 +8361,8 @@ echo "$as_me: error: cannot create directory \"$ac_dir\"" >&2;}
   fi
   # Run the commands associated with the file.
   case $ac_file in
-    src/MoochoUtilities/TSFCoreUtilsConfig.h ) # update the timestamp
-echo 'timestamp for src/MoochoUtilities/TSFCoreUtilsConfig.h:src/MoochoUtilities/TSFCoreUtilsConfig.h.in' >"src/MoochoUtilities/stamp-h1"
+    src/TSFCoreUtilsConfig.h ) # update the timestamp
+echo 'timestamp for src/TSFCoreUtilsConfig.h:src/TSFCoreUtilsConfig.h.in' >"src/stamp-h1"
  ;;
   esac
 done
