----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.in aclocal.m4 configure configure.ac src/Makefile.in
 	src/TSFCoreUtilsConfig.h.in src/TSFCoreUtils_ConfigDefs.hpp
 	src/RTOpPack/RTOpServer.hpp src/RTOpPack/RTOpServerDecl.hpp
 	test/Makefile.in test/rcp_test/Makefile.in
 ----------------------------------------------------------------------

 Removed standard headers from RTOpServer files.  Changed configure script
 to find <map> and include it in TSFCoreUtils_ConfigDefs.hpp.  Then package was
 bootstrapped.  With these changes TSFCoreUtils compiles on a GNU 2.96 compiler.

diff --git a/packages/TSFCoreUtils/configure b/packages/TSFCoreUtils/configure
--- a/packages/TSFCoreUtils/configure
+++ b/packages/TSFCoreUtils/configure
@@ -4731,7 +4731,11 @@ done
 
 
 
-for ac_header in string string.h malloc.h sstream stdexcept
+
+
+
+
+for ac_header in string string.h malloc.h sstream stdexcept map map.h vector vector.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -5021,62 +5025,74 @@ done
 
 
 if test "X$ac_cv_header_cstdlib" != "Xyes" && test "X$ac_cv_header_stdlib_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find cstdlib or stdlib.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find cstdlib or stdlib.h.  New_Package requires at least one or the other." >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find cstdlib or stdlib.h.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find cstdlib or stdlib.h.  TSFCoreUtils requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_cstdio" != "Xyes" && test "X$ac_cv_header_stdio_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find cstdio or stdio.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find cstdio or stdio.h.  New_Package requires at least one or the other." >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find cstdio or stdio.h.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find cstdio or stdio.h.  TSFCoreUtils requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_cassert" != "Xyes" && test "X$ac_cv_header_assert_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find cassert or assert.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find cassert or assert.h.  New_Package requires at least one or the other." >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find cassert or assert.h.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find cassert or assert.h.  TSFCoreUtils requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_string" != "Xyes" && test "X$ac_cv_header_string_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find string or string.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find string or string.h.  New_Package requires at least one or the other." >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find string or string.h.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find string or string.h.  TSFCoreUtils requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_ostream" != "Xyes" && test "X$ac_cv_header_iostream" != "Xyes" && test "X$ac_cv_header_iostream_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find iostream or iostream.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find iostream or iostream.h.  New_Package requires at least one or the other." >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find iostream or iostream.h.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find iostream or iostream.h.  TSFCoreUtils requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_cmath" != "Xyes" && test "X$ac_cv_header_math_h" != "Xyes"; then
-    { { echo "$as_me:$LINENO: error: Cannot find cmath or math.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find cmath or math.h.  New_Package requires at least one or the other." >&2;}
+    { { echo "$as_me:$LINENO: error: Cannot find cmath or math.h.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find cmath or math.h.  TSFCoreUtils requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_iomanip" != "Xyes" && test "X$ac_cv_header_iomanip_h" != "Xyes"; then
-    { { echo "$as_me:$LINENO: error: Cannot find iomanip or iomanip.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find iomanip or iomanip.h.  New_Package requires at least one or the other." >&2;}
+    { { echo "$as_me:$LINENO: error: Cannot find iomanip or iomanip.h.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find iomanip or iomanip.h.  TSFCoreUtils requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_malloc_h" != "Xyes"; then
-    { { echo "$as_me:$LINENO: error: Cannot find malloc.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find malloc.h.  New_Package requires at least one or the other." >&2;}
+    { { echo "$as_me:$LINENO: error: Cannot find malloc.h.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find malloc.h.  TSFCoreUtils requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_stdexcept" != "Xyes"; then
-    { { echo "$as_me:$LINENO: error: Cannot find stdexcept.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find stdexcept.  New_Package requires at least one or the other." >&2;}
+    { { echo "$as_me:$LINENO: error: Cannot find stdexcept.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find stdexcept.  TSFCoreUtils requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_memory" != "Xyes" && test "X$ac_cv_header_memory_h" != "Xyes"; then
-    { { echo "$as_me:$LINENO: error: Cannot find memory or memory.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find memory or memory.h.  New_Package requires at least one or the other." >&2;}
+    { { echo "$as_me:$LINENO: error: Cannot find memory or memory.h.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find memory or memory.h.  TSFCoreUtils requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_map" != "Xyes" && test "X$ac_cv_header_map_h" != "Xyes"; then
+    { { echo "$as_me:$LINENO: error: Cannot find map or map.h.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find map or map.h.  TSFCoreUtils requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_vector" != "Xyes" && test "X$ac_cv_header_vector_h" != "Xyes"; then
+    { { echo "$as_me:$LINENO: error: Cannot find vector or vector.h.  TSFCoreUtils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find vector or vector.h.  TSFCoreUtils requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -5736,7 +5752,7 @@ fi
 # a cpp #define command and one or more source or header files  - ie
 # conditional compilation which requires a change to the makefile.
 # If configure is called with "--enable-newp_swahili", it will place
-# a #define HAVE_NEWP_SWAHILI in New_Package_config.h and add source
+# a #define HAVE_NEWP_SWAHILI in TSFCoreUtils_config.h and add source
 # and header files as specified in Makefile.am
 #
 # To add an option to your package, you will need to modify this file
@@ -5746,7 +5762,7 @@ fi
 # TAC_ARG_ENABLE_OPTION performs several tasks, including:
 #   1)  Setting a help string
 #   2)  Printing a message to standard out
-#   3)  Defining HAVE_NEWP_SWAHILI (For use in New_Package_config.h)
+#   3)  Defining HAVE_NEWP_SWAHILI (For use in TSFCoreUtils_config.h)
 #
 # AM_CONDITIONAL makes HAVE_NEWP_SWAHILI available for use in Makefile.am
 # ------------------------------------------------------------------------
@@ -5945,7 +5961,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5948: \"$ac_link\") >&5
+(eval echo $as_me:5964: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6025,7 +6041,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6028: \"$ac_link\") >&5
+(eval echo $as_me:6044: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6928,7 +6944,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:6931: \"$ac_link\") >&5
+(eval echo $as_me:6947: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7008,7 +7024,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7011: \"$ac_link\") >&5
+(eval echo $as_me:7027: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
