----------------------------------------------------------------------
Committing in .

Modified Files:
	Makefile.am Makefile.in aclocal.m4 configure configure.ac
	src/TSFCoreConfig.h.in
Added Files:
	test/Makefile.am test/Makefile.in test/scripts/Makefile.am
	test/scripts/Makefile.in test/scripts/daily/Makefile.am
	test/scripts/daily/Makefile.in
	test/scripts/daily/mpi/Makefile.am
	test/scripts/daily/mpi/Makefile.in
	test/scripts/daily/serial/Makefile.am
	test/scripts/daily/serial/Makefile.in
	test/scripts/weekly/Makefile.am
	test/scripts/weekly/Makefile.in
	test/scripts/weekly/mpi/Makefile.am
	test/scripts/weekly/mpi/Makefile.in
	test/scripts/weekly/serial/Makefile.am
	test/scripts/weekly/serial/Makefile.in
----------------------------------------------------------------------
Added a many of the files necessary to add test harness test to TSFCore.
Now I just have to add shells for the test scripts, bootstrap again, and
it will be ready to turn over to Ross.

diff --git a/packages/TSFCore/configure b/packages/TSFCore/configure
--- a/packages/TSFCore/configure
+++ b/packages/TSFCore/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_TSFCORE_EPETRA_TRUE HAVE_TSFCORE_EPETRA_FALSE HAVE_TSFCORE_MPI_TRUE HAVE_TSFCORE_MPI_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_TSFCORE_EPETRA_TRUE HAVE_TSFCORE_EPETRA_FALSE HAVE_TSFCORE_MPI_TRUE HAVE_TSFCORE_MPI_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -876,6 +876,9 @@ Optional Features:
   --enable-mpi            MPI support
   --enable-tsfcore-epetra enable TSFCore's Epetra adapters (default is no)
   --enable-tsfcore-mpi    enable TSFCore's mpi adapters (default is no)
+  --enable-tests          Build tests for all Trilinos packages (not all
+                          packages are sensitive to this option) (default is
+                          yes)
   --enable-examples       Build examples for all Trilinos packages (not all
                           packages are sensitive to this option) (default is
                           yes)
@@ -3170,7 +3173,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3173:" \
+echo "$as_me:3176:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5673,6 +5676,42 @@ fi
 # ------------------------------------------------------------------------
 
 
+# Check whether --enable-tests or --disable-tests was given.
+if test "${enable_tests+set}" = set; then
+  enableval="$enable_tests"
+  ac_cv_use_tests=$enableval
+else
+  ac_cv_use_tests=yes
+fi;
+
+echo "$as_me:$LINENO: checking whether to use tests" >&5
+echo $ECHO_N "checking whether to use tests... $ECHO_C" >&6
+
+if test "X$ac_cv_use_tests" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TESTS
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_tests" != "Xno"; then
+  BUILD_TESTS_TRUE=
+  BUILD_TESTS_FALSE='#'
+else
+  BUILD_TESTS_TRUE='#'
+  BUILD_TESTS_FALSE=
+fi
+
+
+
 # Check whether --enable-examples or --disable-examples was given.
 if test "${enable_examples+set}" = set; then
   enableval="$enable_examples"
@@ -5802,7 +5841,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5805: \"$ac_link\") >&5
+(eval echo $as_me:5844: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5882,7 +5921,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5885: \"$ac_link\") >&5
+(eval echo $as_me:5924: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8314,7 +8353,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8317: \"$ac_link\") >&5
+(eval echo $as_me:8356: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8394,7 +8433,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8397: \"$ac_link\") >&5
+(eval echo $as_me:8436: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8612,7 +8651,7 @@ fi
 # Output files
 # ------------------------------------------------------------------------
 
-                                                                      ac_config_files="$ac_config_files Makefile src/Makefile example/Makefile example/Nonlin/Makefile example/Nonlin/NP2DSim/Makefile example/Nonlin/NP4DOpt/Makefile example/Solvers/Makefile"
+                                                                                                                                                      ac_config_files="$ac_config_files Makefile src/Makefile example/Makefile example/Nonlin/Makefile example/Nonlin/NP2DSim/Makefile example/Nonlin/NP4DOpt/Makefile example/Solvers/Makefile test/Makefile test/scripts/Makefile test/scripts/daily/Makefile test/scripts/daily/mpi/Makefile test/scripts/daily/serial/Makefile test/scripts/weekly/Makefile test/scripts/weekly/mpi/Makefile test/scripts/weekly/serial/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -8752,6 +8791,13 @@ if test -z "${HAVE_TSFCORE_MPI_TRUE}" && test -z "${HAVE_TSFCORE_MPI_FALSE}"; th
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_TSFCORE_MPI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_TSFCORE_MPI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_TESTS_TRUE}" && test -z "${BUILD_TESTS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9212,6 +9258,14 @@ do
   "example/Nonlin/NP2DSim/Makefile" ) CONFIG_FILES="$CONFIG_FILES example/Nonlin/NP2DSim/Makefile" ;;
   "example/Nonlin/NP4DOpt/Makefile" ) CONFIG_FILES="$CONFIG_FILES example/Nonlin/NP4DOpt/Makefile" ;;
   "example/Solvers/Makefile" ) CONFIG_FILES="$CONFIG_FILES example/Solvers/Makefile" ;;
+  "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
+  "test/scripts/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/scripts/Makefile" ;;
+  "test/scripts/daily/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/scripts/daily/Makefile" ;;
+  "test/scripts/daily/mpi/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/scripts/daily/mpi/Makefile" ;;
+  "test/scripts/daily/serial/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/scripts/daily/serial/Makefile" ;;
+  "test/scripts/weekly/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/scripts/weekly/Makefile" ;;
+  "test/scripts/weekly/mpi/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/scripts/weekly/mpi/Makefile" ;;
+  "test/scripts/weekly/serial/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/scripts/weekly/serial/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "src/TSFCoreConfig.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/TSFCoreConfig.h:src/TSFCoreConfig.h.in" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -9369,6 +9423,8 @@ s,@HAVE_TSFCORE_EPETRA_TRUE@,$HAVE_TSFCORE_EPETRA_TRUE,;t t
 s,@HAVE_TSFCORE_EPETRA_FALSE@,$HAVE_TSFCORE_EPETRA_FALSE,;t t
 s,@HAVE_TSFCORE_MPI_TRUE@,$HAVE_TSFCORE_MPI_TRUE,;t t
 s,@HAVE_TSFCORE_MPI_FALSE@,$HAVE_TSFCORE_MPI_FALSE,;t t
+s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
+s,@BUILD_TESTS_FALSE@,$BUILD_TESTS_FALSE,;t t
 s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
 s,@BUILD_EXAMPLES_FALSE@,$BUILD_EXAMPLES_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
