----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.am Makefile.in aclocal.m4 configure configure.ac
 	example/Makefile.in example/Nonlin/Makefile.in
 	example/Nonlin/NP2DSim/Makefile.am
 	example/Nonlin/NP2DSim/Makefile.in
 	example/Nonlin/NP4DOpt/Makefile.am
 	example/Nonlin/NP4DOpt/Makefile.in example/Solvers/Makefile.am
 	example/Solvers/Makefile.in src/Makefile.in
 	src/TSFCoreConfig.h.in test/Makefile.in
 	test/scripts/Makefile.in test/scripts/daily/Makefile.in
 	test/scripts/daily/mpi/Makefile.in
 	test/scripts/daily/serial/Makefile.in
 	test/scripts/weekly/Makefile.in
 	test/scripts/weekly/mpi/Makefile.in
 	test/scripts/weekly/serial/Makefile.in
 ----------------------------------------------------------------------

 Configure script now looks for the presence of --enable-teuchos-experimental.
 If teuchos-experimental was enabled then the TSFCore examples are built because
 is uses the smart pointer in Teuchos now.  If teuchos-experimental is not enabled,
 then no examples are built.  Furthermore, if tsfcore-epetra is enabled then the
 GMRES solver example is built.  This should address bug #525.

diff --git a/packages/TSFCore/configure b/packages/TSFCore/configure
--- a/packages/TSFCore/configure
+++ b/packages/TSFCore/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_TSFCORE_EPETRA_TRUE HAVE_TSFCORE_EPETRA_FALSE HAVE_TSFCORE_MPI_TRUE HAVE_TSFCORE_MPI_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_TSFCORE_EPETRA_TRUE HAVE_TSFCORE_EPETRA_FALSE HAVE_TSFCORE_MPI_TRUE HAVE_TSFCORE_MPI_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE BUILD_TEUCHOS_EXPERIMENTAL_TRUE BUILD_TEUCHOS_EXPERIMENTAL_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -882,6 +882,9 @@ Optional Features:
   --enable-examples       Build examples for all Trilinos packages (not all
                           packages are sensitive to this option) (default is
                           yes)
+  --enable-teuchos-experimental
+                          Build TSFCore's examples which use
+                          teuchos-experimental (default is no)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -3173,7 +3176,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3176:" \
+echo "$as_me:3179:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5747,6 +5750,42 @@ else
 fi
 
 
+
+# Check whether --enable-teuchos-experimental or --disable-teuchos-experimental was given.
+if test "${enable_teuchos_experimental+set}" = set; then
+  enableval="$enable_teuchos_experimental"
+  ac_cv_use_teuchos_experimental=$enableval
+else
+  ac_cv_use_teuchos_experimental=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use teuchos-experimental" >&5
+echo $ECHO_N "checking whether to use teuchos-experimental... $ECHO_C" >&6
+
+if test "X$ac_cv_use_teuchos_experimental" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TEUCHOS_EXPERIMENTAL
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_teuchos_experimental" != "Xno"; then
+  BUILD_TEUCHOS_EXPERIMENTAL_TRUE=
+  BUILD_TEUCHOS_EXPERIMENTAL_FALSE='#'
+else
+  BUILD_TEUCHOS_EXPERIMENTAL_TRUE='#'
+  BUILD_TEUCHOS_EXPERIMENTAL_FALSE=
+fi
+
+
 # ------------------------------------------------------------------------
 # Specify other directories
 # ------------------------------------------------------------------------
@@ -5841,7 +5880,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5844: \"$ac_link\") >&5
+(eval echo $as_me:5883: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5921,7 +5960,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5924: \"$ac_link\") >&5
+(eval echo $as_me:5963: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8353,7 +8392,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8356: \"$ac_link\") >&5
+(eval echo $as_me:8395: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8433,7 +8472,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8436: \"$ac_link\") >&5
+(eval echo $as_me:8475: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8805,6 +8844,13 @@ if test -z "${BUILD_EXAMPLES_TRUE}" && test -z "${BUILD_EXAMPLES_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_EXAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_EXAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_TEUCHOS_EXPERIMENTAL_TRUE}" && test -z "${BUILD_TEUCHOS_EXPERIMENTAL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_TEUCHOS_EXPERIMENTAL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_TEUCHOS_EXPERIMENTAL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9427,6 +9473,8 @@ s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
 s,@BUILD_TESTS_FALSE@,$BUILD_TESTS_FALSE,;t t
 s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
 s,@BUILD_EXAMPLES_FALSE@,$BUILD_EXAMPLES_FALSE,;t t
+s,@BUILD_TEUCHOS_EXPERIMENTAL_TRUE@,$BUILD_TEUCHOS_EXPERIMENTAL_TRUE,;t t
+s,@BUILD_TEUCHOS_EXPERIMENTAL_FALSE@,$BUILD_TEUCHOS_EXPERIMENTAL_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
 s,@BLAS_LIBS@,$BLAS_LIBS,;t t
 s,@LAPACK_LIBS@,$LAPACK_LIBS,;t t
