----------------------------------------------------------------------
Committing in .

Modified Files:
	aclocal.m4 configure configure.ac src/TSFCoreConfig.h.in
----------------------------------------------------------------------
Edited configure.ac to search for headers used in TSFCore.  The original
file was taken from another package and the list of headers used still
corresponded to the other package.  Also cleaned out some other garbage,
mostly comments from the previous package.

diff --git a/packages/TSFCore/configure b/packages/TSFCore/configure
--- a/packages/TSFCore/configure
+++ b/packages/TSFCore/configure
@@ -857,7 +857,6 @@ Optional Features:
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
   --enable-mpi            MPI support
-  --enable-newp_swahili   enable swahili support (default is no)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -2900,7 +2899,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:2903:" \
+echo "$as_me:2902:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -3889,11 +3888,8 @@ rm -f conftest.err conftest.$ac_ext
 fi
 
 
-#  #np# - Customize the checks for headers needed in package being added.
-#NOTE: This section still needs to be updated for TSFCore, it is still
-# code from Epetra
 # ------------------------------------------------------------------------
-# Checks for header files - used in Epetra_ConfigDefs.h
+# Checks for header files
 # ------------------------------------------------------------------------
 
 echo "$as_me:$LINENO: checking for ANSI C header files" >&5
@@ -4097,9 +4093,7 @@ done
 
 
 
-
-
-for ac_header in cstdlib stdlib.h cstdio stdio.h cassert assert.h
+for ac_header in stdexcept typeinfo cassert assert.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -4216,9 +4210,7 @@ done
 
 
 
-
-
-for ac_header in cmath math.h iomanip iomanip.h iostream iostream.h
+for ac_header in vector memory string string.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -4332,130 +4324,15 @@ fi
 done
 
 
-
-for ac_header in string string.h
-do
-as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking $ac_header usability" >&5
-echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-$ac_includes_default
-#include <$ac_header>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_header_compiler=no
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
-
-# Is the header present?
-echo "$as_me:$LINENO: checking $ac_header presence" >&5
-echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-#include <$ac_header>
-_ACEOF
-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-  ac_status=$?
-  egrep -v '^ *\+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null; then
-  if test -s conftest.err; then
-    ac_cpp_err=$ac_cxx_preproc_warn_flag
-  else
-    ac_cpp_err=
-  fi
-else
-  ac_cpp_err=yes
-fi
-if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  ac_header_preproc=no
-fi
-rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc in
-  yes:no )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;};;
-  no:yes )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
-echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: $ac_header: check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;};;
-esac
-echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  eval "$as_ac_Header=$ac_header_preproc"
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
-
-fi
-if test `eval echo '${'$as_ac_Header'}'` = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
-_ACEOF
-
-fi
-
-done
-
-
-if test "X$ac_cv_header_cstdlib" != "Xyes" && test "X$ac_cv_header_stdlib_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find cstdlib or stdlib.h.  TSFCore requires at least one or the other." >&5
-echo "$as_me: error: Cannot find cstdlib or stdlib.h.  TSFCore requires at least one or the other." >&2;}
+if test "X$ac_cv_header_stdexcept" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find stdexcept.  TSFCore requires this header file." >&5
+echo "$as_me: error: Cannot find stdexcept.  TSFCore requires this header file." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-if test "X$ac_cv_header_cstdio" != "Xyes" && test "X$ac_cv_header_stdio_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find cstdio or stdio.h.  TSFCore requires at least one or the other." >&5
-echo "$as_me: error: Cannot find cstdio or stdio.h.  TSFCore requires at least one or the other." >&2;}
+if test "X$ac_cv_header_typeinfo" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find typeinfo.  TSFCore requires this header file." >&5
+echo "$as_me: error: Cannot find typeinfo.  TSFCore requires this header file." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -4465,31 +4342,22 @@ echo "$as_me: error: Cannot find cassert or assert.h.  TSFCore requires at least
    { (exit 1); exit 1; }; }
 fi
 
+if test "X$ac_cv_header_vector" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find vector.  TSFCore requires this header file." >&5
+echo "$as_me: error: Cannot find vector.  TSFCore requires this header file." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_memory" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find memory.  TSFCore requires this header file." >&5
+echo "$as_me: error: Cannot find memory.  TSFCore requires this header file." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 if test "X$ac_cv_header_string" != "Xyes" && test "X$ac_cv_header_string_h" != "Xyes"; then
   { { echo "$as_me:$LINENO: error: Cannot find string or string.h.  TSFCore requires at least one or the other." >&5
 echo "$as_me: error: Cannot find string or string.h.  TSFCore requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
-fi
-
-if test "X$ac_cv_header_iostream" != "Xyes" && test "X$ac_cv_header_iostream_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find iostream or iostream.h.  TSFCore requires at least one or the other." >&5
-echo "$as_me: error: Cannot find iostream or iostream.h.  TSFCore requires at least one or the other." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-if test "X${host}" != "Xtflop"; then
-  if test "X$ac_cv_header_cmath" != "Xyes" && test "X$ac_cv_header_math_h" != "Xyes"; then
-    { { echo "$as_me:$LINENO: error: Cannot find cmath or math.h.  TSFCore requires at least one or the other." >&5
-echo "$as_me: error: Cannot find cmath or math.h.  TSFCore requires at least one or the other." >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-else
-  # TFLOP
-  if test "X$ac_cv_header_iomanip" != "Xyes" && test "X$ac_cv_header_iomanip_h" != "Xyes"; then
-    { { echo "$as_me:$LINENO: error: Cannot find iomanip or iomanip.h.  TSFCore requires at least one or the other." >&5
-echo "$as_me: error: Cannot find iomanip or iomanip.h.  TSFCore requires at least one or the other." >&2;}
-   { (exit 1); exit 1; }; }
-  fi
 fi
 
 # Checks for typedefs, structures, and compiler characteristics.
@@ -5110,7 +4978,6 @@ _ACEOF
 
 fi
 
-#AC_CXX_STD_IOS_BASE_FMTFLAGS
 echo "$as_me:$LINENO: checking whether the compiler recognizes std::sprintf as supported IO function" >&5
 echo $ECHO_N "checking whether the compiler recognizes std::sprintf as supported IO function... $ECHO_C" >&6
 if test "${ac_cv_cxx_std_sprintf+set}" = set; then
@@ -5243,87 +5110,6 @@ fi
 # ------------------------------------------------------------------------
 
 # ------------------------------------------------------------------------
-# #np# newp_swahili is an example of a package feature which requires both
-# a cpp #define command and one or more source or header files  - ie
-# conditional compilation which requires a change to the makefile.
-# If configure is called with "--enable-newp_swahili", it will place
-# a #define HAVE_NEWP_SWAHILI in New_Package_config.h and add source
-# and header files as specified in Makefile.am
-#
-# To add an option to your package, you will need to modify this file
-# (i.e. configure.ac), and src/Makefile.am.  A bootstrap is also required.
-# Look for SWAHILI in both files listed above.
-#
-# TAC_ARG_ENABLE_OPTION performs several tasks, including:
-#   1)  Setting a help string
-#   2)  Printing a message to standard out
-#   3)  Defining HAVE_NEWP_SWAHILI (For use in New_Package_config.h)
-#
-# AM_CONDITIONAL makes HAVE_NEWP_SWAHILI available for use in Makefile.am
-# ------------------------------------------------------------------------
-#
-
-# Check whether --enable-newp_swahili or --disable-newp_swahili was given.
-if test "${enable_newp_swahili+set}" = set; then
-  enableval="$enable_newp_swahili"
-  ac_cv_use_newp_swahili=$enableval
-else
-  ac_cv_use_newp_swahili=no
-fi;
-
-echo "$as_me:$LINENO: checking whether to use newp_swahili" >&5
-echo $ECHO_N "checking whether to use newp_swahili... $ECHO_C" >&6
-
-if test "X$ac_cv_use_newp_swahili" != "Xno"; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_NEWP_SWAHILI 1
-_ACEOF
-
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
-
-if test "X$ac_cv_use_newp_swahili" != "Xno"; then
-  HAVE_NEWP_SWAHILI_TRUE=
-  HAVE_NEWP_SWAHILI_FALSE='#'
-else
-  HAVE_NEWP_SWAHILI_TRUE='#'
-  HAVE_NEWP_SWAHILI_FALSE=
-fi
-
-# ------------------------------------------------------------------------
-# Checks for special package flags
-# ------------------------------------------------------------------------
-
-#
-#  #np# - These options are specific to Epetra and are left only as examples.
-#         If uncommented, the following lines would define HAVE_FATAL_MESSAGES
-#         in the (package)_config.h file.  Developers should use a
-#         more specific name such as 'new_package-fatal_messages', rather
-#         than 'fatal_messages'.
-#TAC_ARG_ENABLE_OPTION(fatal_messages, [enable printing of fatal error messages],
-#                   FATAL_MESSAGES, yes)
-#TAC_ARG_ENABLE_OPTION(warning_messages, [enable printing of warning error messages],
-#                   WARNING_MESSAGES, no)
-#TAC_ARG_ENABLE_OPTION(format_io, [Use package-defined IO formatting for output],
-#                   FORMAT_IO, yes)
-
-#  #np# - These are specific to Epetra and are left only as examples.
-#         If uncommented, the following line would define HAVE_ZOLTAN in
-#         the (package)_config.h file.  Developers should use a more
-#         specific name such as 'new_package-zoltan', rather than 'zoltan'.
-# TAC_ARG_WITH_PACKAGE(zoltan, [Enable Zoltan interface support], ZOLTAN, no)
-# TAC_ARG_WITH_PACKAGE(rtop, [Enable RTOp interface support], RTOP, no)
-# TAC_ARG_WITH_PACKAGE(esi, [Enable ESI interface support], ESI, yes)
-# TAC_ARG_WITH_PACKAGE(superlu, [Enable SuperLU interface support], SUPERLU, no)
-
-# ------------------------------------------------------------------------
 # Specify other directories
 # ------------------------------------------------------------------------
 
@@ -5417,7 +5203,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5420: \"$ac_link\") >&5
+(eval echo $as_me:5206: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5496,7 +5282,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5499: \"$ac_link\") >&5
+(eval echo $as_me:5285: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6351,7 +6137,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:6354: \"$ac_link\") >&5
+(eval echo $as_me:6140: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6430,7 +6216,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6433: \"$ac_link\") >&5
+(eval echo $as_me:6219: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7283,8 +7069,6 @@ s,@USE_ALTERNATE_AR_TRUE@,$USE_ALTERNATE_AR_TRUE,;t t
 s,@USE_ALTERNATE_AR_FALSE@,$USE_ALTERNATE_AR_FALSE,;t t
 s,@ALTERNATE_AR@,$ALTERNATE_AR,;t t
 s,@CXXCPP@,$CXXCPP,;t t
-s,@HAVE_NEWP_SWAHILI_TRUE@,$HAVE_NEWP_SWAHILI_TRUE,;t t
-s,@HAVE_NEWP_SWAHILI_FALSE@,$HAVE_NEWP_SWAHILI_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
 s,@ac_aux_dir@,$ac_aux_dir,;t t
 CEOF
