----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.in aclocal.m4 configure configure.ac
 	example/Makefile.in example/Nonlin/Makefile.in
 	example/Nonlin/NP2DSim/Makefile.am
 	example/Nonlin/NP2DSim/Makefile.in
 	example/Nonlin/NP4DOpt/Makefile.am
 	example/Nonlin/NP4DOpt/Makefile.in src/Makefile.am
 	src/Makefile.in src/TSFCoreConfig.h.in
 	src/interfaces/Core/TSFCoreAssertOp.hpp
 	src/interfaces/Core/TSFCoreLinearOp.hpp
 	src/interfaces/Core/TSFCoreMultiVectorColsDecl.hpp
 	src/interfaces/Core/TSFCoreMultiVectorStdOps.hpp
 	src/interfaces/Core/TSFCoreOpBase.hpp
 	src/interfaces/Core/TSFCoreSerialVector.hpp
 	src/interfaces/Core/TSFCoreSerialVectorBase.hpp
 	src/interfaces/Core/TSFCoreSerialVectorSpace.hpp
 	src/interfaces/Core/TSFCoreSerialVectorSpaceFactory.hpp
 	src/interfaces/Core/TSFCoreTypes.hpp
 	src/interfaces/Core/TSFCoreVector.hpp
 	src/interfaces/Core/TSFCoreVectorDecl.hpp
 	src/interfaces/Core/TSFCoreVectorStdOps.hpp
 	src/interfaces/Core/TSFCore_apply_op_helper.hpp
 	src/interfaces/Nonlin/TSFCoreNonlinLinearOpWithSolve.hpp
 	src/interfaces/Nonlin/TSFCoreNonlinLinearSolveOp.hpp
 	src/interfaces/Solvers/TSFCoreSolversNorm.hpp
 	src/utilities/Makefile.am
 	src/utilities/Core/TSFCoreExplicitVectorView.hpp
 	src/utilities/Core/TSFCoreMultiVectorAllocator.hpp
 	src/utilities/Core/TSFCoreTestingTools.hpp
 	src/utilities/Core/TSFCoreTestingToolsDecl.hpp
 	src/utilities/Nonlin/TSFCoreNonlinNonlinearProblemFirstOrderTester.hpp
 	src/utilities/Nonlin/TSFCoreNonlinNonlinearProblemFirstOrderTesterDecl.hpp
 	src/utilities/Nonlin/TSFCoreNonlinNonlinearProblemTester.hpp
 	src/utilities/Nonlin/TSFCoreNonlinNonlinearProblemTesterDecl.hpp
 	src/utilities/Nonlin/TSFCoreNonlinSimpleNewtonSolver.hpp
 	src/utilities/Nonlin/TSFCoreNonlinSimpleNewtonSolverDecl.hpp
 	src/utilities/Solvers/TSFCoreSolversBiCGSolver.hpp
 	src/utilities/Solvers/TSFCoreSolversBiCGSolverDecl.hpp
 	src/utilities/Solvers/TSFCoreSolversNormedConvergenceTester.hpp
 	src/utilities/Solvers/TSFCoreSolversNormedConvergenceTesterDecl.hpp
 ----------------------------------------------------------------------

 Changed headers to use the configured header TSFCore_ConfigDefs.hpp.

diff --git a/packages/TSFCore/configure b/packages/TSFCore/configure
--- a/packages/TSFCore/configure
+++ b/packages/TSFCore/configure
@@ -4440,7 +4440,8 @@ done
 
 
 
-for ac_header in stdexcept typeinfo cassert assert.h
+
+for ac_header in ostream iostream iostream.h iomanip iomanip.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -4585,7 +4586,8 @@ done
 
 
 
-for ac_header in vector memory string string.h
+
+for ac_header in valarray stdexcept typeinfo cassert assert.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -4726,6 +4728,170 @@ fi
 
 done
 
+
+
+
+
+
+for ac_header in vector algorithm memory string string.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
+
+
+if test "X$ac_cv_header_ostream" != "Xyes" && test "X$ac_cv_header_iostream" != "Xyes" && "X$ac_cv_header_iostream_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find ostream, iostream, or iostream.h.  TSFCore requires at least one or the other." >&5
+echo "$as_me: error: Cannot find ostream, iostream, or iostream.h.  TSFCore requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_iomanip" != "Xyes" && "X$ac_cv_header_iomanip_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find iomanip or iomanip.h.  TSFCore requires this header file." >&5
+echo "$as_me: error: Cannot find iomanip or iomanip.h.  TSFCore requires this header file." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_valarray" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find valarray.  TSFCore requires this header file." >&5
+echo "$as_me: error: Cannot find valarray.  TSFCore requires this header file." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 if test "X$ac_cv_header_stdexcept" != "Xyes"; then
   { { echo "$as_me:$LINENO: error: Cannot find stdexcept.  TSFCore requires this header file." >&5
@@ -4748,6 +4914,12 @@ fi
 if test "X$ac_cv_header_vector" != "Xyes"; then
   { { echo "$as_me:$LINENO: error: Cannot find vector.  TSFCore requires this header file." >&5
 echo "$as_me: error: Cannot find vector.  TSFCore requires this header file." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_algorithm" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find algorithm.  TSFCore requires this header file." >&5
+echo "$as_me: error: Cannot find algorithm.  TSFCore requires this header file." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -5581,7 +5753,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5584: \"$ac_link\") >&5
+(eval echo $as_me:5756: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5661,7 +5833,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5664: \"$ac_link\") >&5
+(eval echo $as_me:5836: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6564,7 +6736,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:6567: \"$ac_link\") >&5
+(eval echo $as_me:6739: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6644,7 +6816,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6647: \"$ac_link\") >&5
+(eval echo $as_me:6819: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
