Added some examples on Tpetra.

diff --git a/packages/didasko/configure b/packages/didasko/configure
--- a/packages/didasko/configure
+++ b/packages/didasko/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_DIDASKO_EPETRA_TRUE HAVE_DIDASKO_EPETRA_FALSE HAVE_DIDASKO_EPETRAEXT_TRUE HAVE_DIDASKO_EPETRAEXT_FALSE HAVE_DIDASKO_NOX_TRUE HAVE_DIDASKO_NOX_FALSE HAVE_DIDASKO_ML_TRUE HAVE_DIDASKO_ML_FALSE HAVE_DIDASKO_AMESOS_TRUE HAVE_DIDASKO_AMESOS_FALSE HAVE_DIDASKO_IFPACK_TRUE HAVE_DIDASKO_IFPACK_FALSE HAVE_DIDASKO_TEUCHOS_TRUE HAVE_DIDASKO_TEUCHOS_FALSE HAVE_DIDASKO_ANASAZI_TRUE HAVE_DIDASKO_ANASAZI_FALSE HAVE_DIDASKO_TRIUTILS_TRUE HAVE_DIDASKO_TRIUTILS_FALSE HAVE_DIDASKO_AZTECOO_TRUE HAVE_DIDASKO_AZTECOO_FALSE HAVE_DIDASKO_LATEX_TRUE HAVE_DIDASKO_LATEX_FALSE BUILD_ZOLTAN_TRUE BUILD_ZOLTAN_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_DIDASKO_EPETRA_TRUE HAVE_DIDASKO_EPETRA_FALSE HAVE_DIDASKO_EPETRAEXT_TRUE HAVE_DIDASKO_EPETRAEXT_FALSE HAVE_DIDASKO_NOX_TRUE HAVE_DIDASKO_NOX_FALSE HAVE_DIDASKO_ML_TRUE HAVE_DIDASKO_ML_FALSE HAVE_DIDASKO_AMESOS_TRUE HAVE_DIDASKO_AMESOS_FALSE HAVE_DIDASKO_IFPACK_TRUE HAVE_DIDASKO_IFPACK_FALSE HAVE_DIDASKO_TEUCHOS_TRUE HAVE_DIDASKO_TEUCHOS_FALSE HAVE_DIDASKO_ANASAZI_TRUE HAVE_DIDASKO_ANASAZI_FALSE HAVE_DIDASKO_TRIUTILS_TRUE HAVE_DIDASKO_TRIUTILS_FALSE HAVE_DIDASKO_AZTECOO_TRUE HAVE_DIDASKO_AZTECOO_FALSE HAVE_DIDASKO_LATEX_TRUE HAVE_DIDASKO_LATEX_FALSE BUILD_ZOLTAN_TRUE BUILD_ZOLTAN_FALSE HAVE_DIDASKO_TPETRA_TRUE HAVE_DIDASKO_TPETRA_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -891,6 +891,7 @@ Optional Features:
   --enable-epetraext-zoltan
                           Enable EpetraExt interface support for Zoltan
                           (default is no)
+  --enable-tpetra         Enables TPETRA examples.
   --enable-examples       Build examples for all Trilinos packages (not all
                           packages are sensitive to this option) (default is
                           yes)
@@ -3809,7 +3810,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3812:" \
+echo "$as_me:3813:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7132,6 +7133,42 @@ else
 fi
 
 
+
+# Check whether --enable-tpetra or --disable-tpetra was given.
+if test "${enable_tpetra+set}" = set; then
+  enableval="$enable_tpetra"
+  ac_cv_use_tpetra=$enableval
+else
+  ac_cv_use_tpetra=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to build optional tpetra dependent code" >&5
+echo $ECHO_N "checking whether to build optional tpetra dependent code... $ECHO_C" >&6
+
+if test "X$ac_cv_use_tpetra" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DIDASKO_TPETRA 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_tpetra" = "Xyes"; then
+  HAVE_DIDASKO_TPETRA_TRUE=
+  HAVE_DIDASKO_TPETRA_FALSE='#'
+else
+  HAVE_DIDASKO_TPETRA_TRUE='#'
+  HAVE_DIDASKO_TPETRA_FALSE=
+fi
+
+#
 # ------------------------------------------------------------------------
 # Checks if tests and examples should be built
 # ------------------------------------------------------------------------
@@ -7398,7 +7435,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:7401: \"$ac_link\") >&5
+(eval echo $as_me:7438: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7476,7 +7513,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7479: \"$ac_link\") >&5
+(eval echo $as_me:7516: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10353,7 +10390,7 @@ fi
 #  of tests.  New package comes only with src and example.
 #  You will need to change AC_CONFIG_FILES below and Makefile.am
 #  to add a new directory.
-                                                                                                                                                                ac_config_files="$ac_config_files Makefile Makefile.export doc/Makefile examples/Makefile examples/amesos/Makefile examples/anasazi/Makefile examples/aztecoo/Makefile examples/epetra/Makefile examples/epetraext/Makefile examples/ifpack/Makefile examples/ml/Makefile examples/nox/Makefile examples/teuchos/Makefile examples/triutils/Makefile examples/HBMatrices/Makefile test/Makefile"
+                                                                                                                                                                          ac_config_files="$ac_config_files Makefile Makefile.export doc/Makefile examples/Makefile examples/amesos/Makefile examples/anasazi/Makefile examples/aztecoo/Makefile examples/epetra/Makefile examples/epetraext/Makefile examples/ifpack/Makefile examples/ml/Makefile examples/nox/Makefile examples/teuchos/Makefile examples/triutils/Makefile examples/HBMatrices/Makefile examples/tpetra/Makefile test/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -10577,6 +10614,13 @@ if test -z "${BUILD_ZOLTAN_TRUE}" && test -z "${BUILD_ZOLTAN_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_ZOLTAN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_ZOLTAN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_DIDASKO_TPETRA_TRUE}" && test -z "${HAVE_DIDASKO_TPETRA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_DIDASKO_TPETRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_DIDASKO_TPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -11053,6 +11097,7 @@ do
   "examples/teuchos/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/teuchos/Makefile" ;;
   "examples/triutils/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/triutils/Makefile" ;;
   "examples/HBMatrices/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/HBMatrices/Makefile" ;;
+  "examples/tpetra/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/tpetra/Makefile" ;;
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "src/Didasko_config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/Didasko_config.h:src/Didasko_config.h.in" ;;
@@ -11239,6 +11284,8 @@ s,@HAVE_DIDASKO_LATEX_TRUE@,$HAVE_DIDASKO_LATEX_TRUE,;t t
 s,@HAVE_DIDASKO_LATEX_FALSE@,$HAVE_DIDASKO_LATEX_FALSE,;t t
 s,@BUILD_ZOLTAN_TRUE@,$BUILD_ZOLTAN_TRUE,;t t
 s,@BUILD_ZOLTAN_FALSE@,$BUILD_ZOLTAN_FALSE,;t t
+s,@HAVE_DIDASKO_TPETRA_TRUE@,$HAVE_DIDASKO_TPETRA_TRUE,;t t
+s,@HAVE_DIDASKO_TPETRA_FALSE@,$HAVE_DIDASKO_TPETRA_FALSE,;t t
 s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
 s,@BUILD_EXAMPLES_FALSE@,$BUILD_EXAMPLES_FALSE,;t t
 s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
